stages:
  - build

build:
  stage: build
  script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --network=host -t $CI_REGISTRY/oscar/onos:2.5 .
    - docker push $CI_REGISTRY/oscar/onos:2.5
  tags:
    - SONA
  timeout: 3 hours